### ISSUE TITLE
Two tests failed during zef install

### ISSUE THREAD

**Issue by hkdtam** [frithnanth/raku-Math-Libgsl-Matrix#4]
Hi Fernando,

Thanks for your nice module. Just for your information when I tried to install it and got the following errors,

```===> Testing [OK] for Math::Libgsl::Constants:ver<0.0.8>:auth<cpan:FRITH>
===> Testing: Math::Libgsl::Matrix:ver<0.3.2>:auth<cpan:FRITH>
[Math::Libgsl::Matrix]     # Failed test 'alias array view as an anomymous sub'
[Math::Libgsl::Matrix]     # at t/03-vector.rakutest line 100
[Math::Libgsl::Matrix]     # expected: $(2e0, 1e0, 1e0, 1e0, 1e0, 1e0, 1e0, 1e0, 1e0, 1e0)
[Math::Libgsl::Matrix]     #      got: $(2e0, 1e0, 1e0, 1e0, 1e0, 0e0, 0e0, 0e0, 0e0, 0e0)
[Math::Libgsl::Matrix]     # You failed 1 test of 25
[Math::Libgsl::Matrix] # Failed test 'views'
[Math::Libgsl::Matrix] # at t/03-vector.rakutest line 50
[Math::Libgsl::Matrix] # You failed 1 test of 9
===> Testing [FAIL]: Math::Libgsl::Matrix:ver<0.3.2>:auth<cpan:FRITH>
Aborting due to test failure: Math::Libgsl::Matrix:ver<0.3.2>:auth<cpan:FRITH> (use --force-test to override)
```
and here is the Raku version,
```raku -v
Welcome to Rakudo(tm) v2020.12.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.12.
```
Thanks in advance for the help.

Regards,
hkdtam

**Comment by frithnanth** [comment]
Hi,
are you using Linux, OSX, or Windows?
And what version of the libgsl is installed on your system?
I test the module on both GitHub and TravisCI, using libgsl 2.5, and on my computer using libgsl 2.6, without any problem, so my wild guess is on a different version of libgsl.

**Comment by hkdtam** [comment]
Hi Fernando,

Thanks for the prompt feedback.

I am using Linux,
```
lsb_release -d
Description:    Debian GNU/Linux 10 (buster)
```
and version of the libgsl,

```
aptitude show libgsl-dev
Package: libgsl-dev
Version: 2.5+dfsg-6
State: installed
Automatically installed: no
Priority: optional
Section: libdevel
Maintainer: Dirk Eddelbuettel <edd@debian.org>
Architecture: amd64
Uncompressed Size: 6852 k
Depends: libgsl23 (= 2.5+dfsg-6), libgslcblas0 (= 2.5+dfsg-6)
Conflicts: gsl-dev, libgsl0-dev
Replaces: gsl-dev, libgsl0 (<= 1.9-4), libgsl0-dev (<= 1.16+dfsg-4)
Provides: libgsl0-dev
```

Thanks in advance.

Regards,
hkdtam.

**Comment by frithnanth** [comment]
Sorry, I can't see any reason why the test should fail, BTW I'm using a Debian sid.
Anyway recently I changed some code in this module, just regarding sub aliasing, I decided to publish a new version on the CPAN, even if it's a minor change and it should not affect the test, but who knows :-)
Probably you need to wait some hours till v0.3.3 reaches all the CPAN servers. Give it a try please.

**Comment by hkdtam** [comment]
Hi Fernando,

All tests passed and thank you very much for the help.

```
 zef install Math::Libgsl::Matrix
===> Searching for: Math::Libgsl::Matrix
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Searching for missing dependencies: Distribution::Builder::MakeFromJSON, Math::Libgsl::Complex, Math::Libgsl::Constants
===> Searching for missing dependencies: System::Query, LibraryMake
===> Searching for missing dependencies: Shell::Command, JSON::Fast
===> Searching for missing dependencies: File::Which, File::Find
===> Building: Math::Libgsl::Complex:ver<0.0.3>:auth<cpan:FRITH>
===> Building [OK] for Math::Libgsl::Complex:ver<0.0.3>:auth<cpan:FRITH>
===> Building: Math::Libgsl::Matrix:ver<0.3.2>:auth<cpan:FRITH>
===> Building [OK] for Math::Libgsl::Matrix:ver<0.3.2>:auth<cpan:FRITH>
===> Testing: JSON::Fast:ver<0.15>
===> Testing [OK] for JSON::Fast:ver<0.15>
===> Testing: System::Query:ver<0.1.4>:auth<github:tony-o>
===> Testing [OK] for System::Query:ver<0.1.4>:auth<github:tony-o>
===> Testing: Distribution::Builder::MakeFromJSON:ver<0.6>:auth<github:niner>
===> Testing [OK] for Distribution::Builder::MakeFromJSON:ver<0.6>:auth<github:niner>
===> Testing: File::Which:ver<1.0.1>
[File::Which] # Found perl6 at '/home/david/.rakudobrew/versions/moar-2020.12/install/bin/perl6'
[File::Which] # Found perl6 at '/home/david/.rakudobrew/versions/moar-2020.12/install/bin/perl6' using whence
===> Testing [OK] for File::Which:ver<1.0.1>
===> Testing: File::Find:ver<0.1.1>
===> Testing [OK] for File::Find:ver<0.1.1>
===> Testing: Shell::Command
===> Testing [OK] for Shell::Command
===> Testing: LibraryMake:ver<1.0.0>
===> Testing [OK] for LibraryMake:ver<1.0.0>
===> Testing: Math::Libgsl::Complex:ver<0.0.3>:auth<cpan:FRITH>
===> Testing [OK] for Math::Libgsl::Complex:ver<0.0.3>:auth<cpan:FRITH>
===> Testing: Math::Libgsl::Constants:ver<0.0.8>:auth<cpan:FRITH>
===> Testing [OK] for Math::Libgsl::Constants:ver<0.0.8>:auth<cpan:FRITH>
===> Testing: Math::Libgsl::Matrix:ver<0.3.2>:auth<cpan:FRITH>
===> Testing [OK] for Math::Libgsl::Matrix:ver<0.3.2>:auth<cpan:FRITH>
===> Installing: JSON::Fast:ver<0.15>
===> Installing: System::Query:ver<0.1.4>:auth<github:tony-o>
===> Installing: Distribution::Builder::MakeFromJSON:ver<0.6>:auth<github:niner>
===> Installing: File::Which:ver<1.0.1>
===> Installing: File::Find:ver<0.1.1>
===> Installing: Shell::Command
===> Installing: LibraryMake:ver<1.0.0>
===> Installing: Math::Libgsl::Complex:ver<0.0.3>:auth<cpan:FRITH>
===> Installing: Math::Libgsl::Constants:ver<0.0.8>:auth<cpan:FRITH>
===> Installing: Math::Libgsl::Matrix:ver<0.3.2>:auth<cpan:FRITH>
```

Regards,
hkdtam.

**Comment by hkdtam** [comment]
Hi Fernando,

Sorry for bothering again.  This is not issue reporting but rather an advice seeking piece so please review only at your convenience.

[Recently I translated](https://rosettacode.org/wiki/Strassen%27s_algorithm#Raku) a [Julia solution](https://rosettacode.org/wiki/Strassen%27s_algorithm#Recursive) of a [Rosetta Code task](https://rosettacode.org/wiki/Strassen%27s_algorithm) with your excellent module.  Of course when you see the code you will surely spot many glaring mistakes, due to my lousy coding skills.

Among all the wrong-doings I would like to ask for your opinion on all those reinvent-the-wheel arithmetic operations first.  The reason I did that was I could not figure out how to make them do pass-by-value instead.  I have tried different approaches like

(\x is copy, y)   or

x.clone.add: y

but I made no progress with all of them.

So in this case what would be the correct/ idiomatic way to handle the problem?

Thanks in advance for your comment and advice.

Regards,
hkdtam.

**Comment by frithnanth** [comment]
If I understand correctly what you wish to accomplish, I would do this:
```raku
use Math::Libgsl::Matrix;

my Math::Libgsl::Matrix $a .= new: 2,2;
my Math::Libgsl::Matrix $b .= new: 2,2;
my Math::Libgsl::Matrix $c .= new: 2,2;
for ^2 X ^2 -> ($i, $j) { $a[$i;$j] = $j + $i * 2 }      # initialize as 0 1 2 3 
for ^2 X ^2 -> ($i, $j) { $b[$i;$j] = $j + $i * 2 + 4 }  # initialize as 4 5 6 7
$c.copy($a).add($b);
for ^2 X ^2 -> ($i,$j) { say $c[$i;$j] }   # output: 4 6 8 10
```
Let me know if I misunderstood your goal.
BTW, I never used the "Discussion" tab and I don't know if it's supposed to be used only for discussions about project management or even for things such as this one; maybe it would be useful for others if the next time you used that, so this stuff is not drowned under a closed issue.

**Comment by hkdtam** [comment]
Hi Fernando,

Thanks for the prompt feedback.

Indeed you nailed the issue, I rewrote it as per your advice,

````
sub infix:<⊕>(\x,\y) { # custom addition
   my Math::Libgsl::Matrix \z .= new: x.size1, x.size2;
   z.copy(x).add(y) 
}
````
and it works as expected.

I didn't even know about the [discussion tab feature](https://docs.github.com/en/github/administering-a-repository/enabling-or-disabling-github-discussions-for-a-repository) and it seems for the purpose exactly as you reckon.  I will use it next time if it is available.

Thanks again.

Regards,
hkdtam.
